services:
  db:
    image: postgres:16-alpine
    container_name: chaek-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chaek
      - POSTGRES_USER=chaek
      - POSTGRES_PASSWORD=chaek
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chaek"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: chaek-app-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "8514:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - ./books:/app/books
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://chaek:chaek@db:5432/chaek
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - AUTH_SECRET=${AUTH_SECRET}

volumes:
  postgres_data_dev:
